### PR TITLE
Fix #63

### LINKED ISSUE #63: Preconditions failure
Hi,

I've found a small bug in TestExecutionImpl. It fails at [#L207](https://github.com/AKSW/RDFUnit/blob/939ae6e747859e422edfaa4b5c562ab68c01d8b6/rdfunit-core/src/main/java/org/aksw/rdfunit/tests/executors/monitors/SimpleTestExecutorMonitor.java#L207)  when the method testingFinished() is called. A value for ExecutionType is required for other methods that uses the same builder. 

Could you, please , give me a hand on it? 

Thank you in advance

### PR DESCRIPTION
**Pull request by sandroacoelho**

### CODE REVIEW

File: rdfunit-model/src/main/java/org/aksw/rdfunit/model/impl/results/TestExecutionImpl.java [hunk 1]
```diff
@@ -114,6 +114,11 @@ public Builder setElement(Resource element) {
             return this;
         }
 
+        public Builder setDefaultExecutionType() {
```
Comment (jimkont) [inline rdfunit-model/src/main/java/org/aksw/rdfunit/model/impl/results/TestExecutionImpl.java]: this can be removed as well

File: rdfunit-core/src/main/java/org/aksw/rdfunit/tests/executors/monitors/SimpleTestExecutorMonitor.java [hunk 2]
```diff
@@ -206,6 +206,7 @@ public void testingFinished() {
                 .setSchemata(schemata)
                 .setTestCaseUris(testCaseUris)
                 .setResults(results)
+                .setDefaultExecutionType()
```
Comment (jimkont) [inline rdfunit-core/src/main/java/org/aksw/rdfunit/tests/executors/monitors/SimpleTestExecutorMonitor.java]: I already set the execution type before, I fixed the bug here yesterday https://github.com/AKSW/RDFUnit/commit/a5bd2f1b6135e41e567a7fbe4e27c128cb17fdab but forgot to push :)
but the test are good

File: rdfunit-core/src/test/java/org/aksw/rdfunit/validate/wrappers/RDFUnitStaticValidatorTest.java [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+import org.aksw.rdfunit.io.reader.RDFReaderException;
+import org.aksw.rdfunit.io.reader.RDFReaderFactory;
+import org.apache.jena.rdf.model.Model;
+import org.apache.jena.riot.Lang;
+import org.junit.Test;
+
+public class RDFUnitStaticValidatorTest {
+
+    @Test
+    public void testValidateModelShaclFullTestCaseResultMode() throws RDFReaderException {
```
Comment (jimkont) [inline rdfunit-core/src/test/java/org/aksw/rdfunit/validate/wrappers/RDFUnitStaticValidatorTest.java]: compilation fails, some classes were renamed e.g. RDFReaderException -> RdfReaderException

**Comment by sandroacoelho** [comment]
rebase done :+1:  
Thanks for the support

**Comment by jimkont** [comment]
Thanks!  :+1:
